# Generated by Django 6.0.6 on 2026-06-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'produits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='uploads/')),
                ('nom_original', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lignes', models.IntegerField()),
                ('lignes_inserees', models.IntegerField()),
                ('lignes_rejetees', models.IntegerField()),
                ('erreurs', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='imports.datasetupload')),
            ],
        ),
    ]
