# Generated by Django 6.0.6 on 2026-06-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
